### ISSUE TITLE
Add Ability to Skip Releases

### ISSUE THREAD

**Issue by korenyoni** [cloudposse/terraform-example-module#13]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

The [`exclude-labels` option](https://github.com/release-drafter/release-drafter#exclude-pull-requests) should be included by default in `auto-release.yaml`

## Expected Behavior

When a PR is merged with a `skip-release` label, a release should not be made.

## Use Case

If a PR does not add any functionality to the actual module, e.g. a README typo fix, then there should be a way to skip the release. Repos using this template should have this ability.

## Describe Ideal Solution

At first I believed that simply setting `exclude-labels` in `.github/auto-release.yaml` will enable this. However that only skips the release from being drafted. A release will still be made because of the [`publish` action input](https://github.com/release-drafter/release-drafter#action-inputs).

The actual solution probably involves detecting the labels in the PR and programatically setting `publish` based on that, within the `auto-release` GitHub Actions workflow.

## Alternatives Considered

N/A

## Additional Context

N/A

**Comment by nitrocode** [comment]
There is a `no-release` label you could use

**Comment by korenyoni** [comment]
@nitrocode this is in [build-harness](https://github.com/cloudposse/build-harness/blob/master/templates/.github/workflows/auto-release.yml) but this template repo's workflows need to be updated.

Will make a PR to update this.
